#!/usr/bin/env ruby

# njp - new jekyll post
# https://github.com/froschi/njp

filename = Time.now.strftime("%F") + '-' + ARGV.collect{|a| a.downcase.delete("^a-z0-9")}.join('-') + '.md'
content = <<eof
---
layout: default
title: '#{ARGV.join(' ')}'
categories: ['update']
published: true
---

# #{ARGV.join(' ')}

Outline of post:

* 
eof

if File.exists?(filename) then
  abort("[-] Sorry, file #{filename} already exists.")
else
  f = File.new(filename, 'w')
  f.puts(content)
  f.close
end
